# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KRC4asxigWbak6UZmbCG6kaqCfyPU5DX
"""



import matplotlib.pyplot as plt
import cv2 as cv
import numpy as np

def normalized_box_filter(img):
  
  Averaging_img = cv.blur(img,(9,1))
  plt.title(" Averaging Blurring")
  plt.imshow(Averaging_img)
  plt.show()
def Gaussian_filter(img):

  Gaussian_img = cv.GaussianBlur(img,(5,5),0)
  plt.title(" Gaussian Blurring")
  plt.imshow(Gaussian_img)
  plt.show()

def median_filter(img):
  # Blurs an image using the median filter
  Median_img = cv.medianBlur(img,5)
  plt.title(" Median Blurring")
  plt.imshow(Median_img)
  plt.show()
def bilateral_filter(img):
#  Blurs an image using the bilateral filter
  Bilateral_img = cv.bilateralFilter(img,9,75,75)
  plt.title(" Bilateral Blurring")
  plt.imshow(Bilateral_img)
  plt.show()