# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KRC4asxigWbak6UZmbCG6kaqCfyPU5DX
"""



import cv2
import numpy as np
from skimage.util import random_noise
import matplotlib.pyplot as plt
import PIL
from PIL import Image, ImageEnhance
def add_noise(img):
  # Add gaussian noise to the original image.
  GaussNoise_image = random_noise(img, mode='gaussian')

  # Add salt noise to the original image.
  SaltNoise_image = random_noise(img, mode='salt')

  # Add pepper noise to the original image.
  PepperNoise_image = random_noise(img, mode='pepper')

  # Add salt-and-pepper noise to the original image.
  SpNoise_image = random_noise(img, mode='s&p')

  # Add gaussian noise with specified local variance at each point of image.
  LocalvarNoise_image = random_noise(img, mode='localvar')

  # Add poisson noise to the original image.
  PoissonNoise_image = random_noise(img, mode='poisson')

  # Add speckle noise to the original image.
  SpeckleNoise_image = random_noise(img, mode='speckle')


  #------------------ Plot -----------------------#

  plt.imshow(img) , plt.title('Original')
  plt.show()
  plt.imshow(GaussNoise_image)   , plt.title('Gaussian')
  plt.show()
  plt.imshow(SaltNoise_image)    , plt.title('Salt')
  plt.show()
  plt.imshow(PepperNoise_image)  , plt.title('Pepper')
  plt.show()
  plt.imshow(SpNoise_image)      , plt.title('Salt and pepper')
  plt.show()
  plt.imshow(LocalvarNoise_image), plt.title('Localvar')
  plt.show()
  plt.imshow(PoissonNoise_image) , plt.title('Poisson')
  plt.show()
  plt.imshow(SpeckleNoise_image) , plt.title('Speckle')
  plt.show()
def denoise_colorimg(img):
  dst = cv2.fastNlMeansDenoisingColored(img,None,40,40,7,21)

  plt.subplot(121),plt.imshow(img)
  plt.subplot(122),plt.imshow(dst)
  plt.show()
def denoise_grayimg(img):
  dst = cv2.fastNlMeansDenoising(img,None,20,7,21)

  plt.subplot(121),plt.imshow(img)
  plt.subplot(122),plt.imshow(dst)
  plt.show()