# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KRC4asxigWbak6UZmbCG6kaqCfyPU5DX
"""



import matplotlib.pyplot as plt
import cv2 as cv
import numpy as np

def sharpening_filter(img):
  # Create a sharpening kernel
  sharpening_filter = np.array([[-1,-1,-1],
                              [-1, 9,-1],
                              [-1,-1,-1]]) 
# Applying kernel(s) to the input image to get the sharpened image
  Sharpened_image = cv.filter2D(img,-1,sharpening_filter)

  plt.title(" Sharpen Image")
  plt.imshow(Sharpened_image)
  plt.show()